# Generated by Django 3.2.5 on 2023-07-01 12:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.TextField(max_length=15)),
                ('placa', models.TextField(max_length=7)),
                ('valor', models.FloatField()),
                ('fornecedor', models.TextField(max_length=15)),
                ('data', models.DateField(default=datetime.datetime.now)),
                ('solicitante', models.TextField(max_length=15)),
                ('autorizado', models.BooleanField(default=False)),
                ('nivel', models.IntegerField(default=1)),
            ],
        ),
    ]
